data_ingestion:
  root_dir : artifacts/data_ingestion
  data_url: "shahriyar1988/wind-farm-data"
  data_dir: artifacts/data_ingestion/data
data_validation:
  data_dir : artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/Validation_satus.txt
data_transformation:
  data_dir: artifacts\data_validation\Validated_data.csv
  root_dir : artifacts\data_transformation
model_training:
  root_dir: artifacts\model_training
  train_data_path: artifacts\data_transformation\train.csv
  metrics_dir: artifacts\model_training\metrics
  model_name: "autoencoder.keras"
classifier_training: 
  root_dir: artifacts\classifier_training
  data_path: artifacts\data_transformation\test.csv
  metrics_dir: artifacts\classifier_training\metrics
  encoder_path: artifacts\model_training\encoder.keras
  model_name: classifier.keras

classifier_evaluation:
  test_data_paths: [artifacts\classifier_training\X_val_cls.npy,artifacts\classifier_training\y_val_cls.npy]
  cls_model_path: artifacts\classifier_training\classifier.keras
  metrics_file_path: artifacts/classifier_evaluation/metircs
