COLUMNS:
  time_stamp: object
  asset_id: int64
  id: int64
  train_test: object
  status_type_id: int64
  sensor_0_avg: float64
  sensor_0_max: float64
  sensor_0_min: float64
  sensor_0_std: float64
  sensor_1_avg: float64
  sensor_1_max: float64
  sensor_1_min: float64
  sensor_1_std: float64
  sensor_2_avg: float64
  sensor_2_max: float64
  sensor_2_min: float64
  sensor_2_std: float64
  sensor_3_avg: float64
  sensor_3_max: float64
  sensor_3_min: float64
  sensor_3_std: float64
  sensor_4_avg: float64
  sensor_4_max: float64
  sensor_4_min: float64
  sensor_4_std: float64
  sensor_5_avg: float64
  sensor_5_max: float64
  sensor_5_min: float64
  sensor_5_std: float64
  sensor_6_avg: float64
  sensor_6_max: float64
  sensor_6_min: float64
  sensor_6_std: float64
  sensor_7_avg: float64
  sensor_7_max: float64
  sensor_7_min: float64
  sensor_7_std: float64
  sensor_8_avg: float64
  sensor_8_max: float64
  sensor_8_min: float64
  sensor_8_std: float64
  sensor_9_avg: float64
  sensor_9_max: float64
  sensor_9_min: float64
  sensor_9_std: float64
  sensor_10_avg: float64
  sensor_10_max: float64
  sensor_10_min: float64
  sensor_10_std: float64
  reactive_power_11_avg: float64
  reactive_power_11_max: float64
  reactive_power_11_min: float64
  reactive_power_11_std: float64
  sensor_12_avg: float64
  sensor_12_max: float64
  sensor_12_min: float64
  sensor_12_std: float64
  sensor_13_avg: float64
  sensor_13_max: float64
  sensor_13_min: float64
  sensor_13_std: float64
  sensor_14_avg: float64
  sensor_14_max: float64
  sensor_14_min: float64
  sensor_14_std: float64
  sensor_15_avg: float64
  sensor_15_max: float64
  sensor_15_min: float64
  sensor_15_std: float64
  sensor_16_avg: float64
  sensor_16_max: float64
  sensor_16_min: float64
  sensor_16_std: float64
  sensor_17_avg: float64
  sensor_17_max: float64
  sensor_17_min: float64
  sensor_17_std: float64
  sensor_18_avg: float64
  sensor_18_max: float64
  sensor_18_min: float64
  sensor_18_std: float64
  sensor_19_avg: float64
  sensor_19_max: float64
  sensor_19_min: float64
  sensor_19_std: float64
  sensor_20_avg: float64
  sensor_20_max: float64
  sensor_20_min: float64
  sensor_20_std: float64
  sensor_21_avg: float64
  sensor_21_max: float64
  sensor_21_min: float64
  sensor_21_std: float64
  sensor_22_avg: float64
  sensor_22_max: float64
  sensor_22_min: float64
  sensor_22_std: float64
  sensor_23_avg: float64
  sensor_23_max: float64
  sensor_23_min: float64
  sensor_23_std: float64
  sensor_24_avg: float64
  sensor_24_max: float64
  sensor_24_min: float64
  sensor_24_std: float64
  sensor_25_avg: float64
  sensor_25_max: float64
  sensor_25_min: float64
  sensor_25_std: float64
  sensor_26_avg: float64
  sensor_26_max: float64
  sensor_26_min: float64
  sensor_26_std: float64
  sensor_27_avg: float64
  sensor_27_max: float64
  sensor_27_min: float64
  sensor_27_std: float64
  sensor_28_avg: float64
  sensor_28_max: float64
  sensor_28_min: float64
  sensor_28_std: float64
  sensor_29_avg: float64
  sensor_29_max: float64
  sensor_29_min: float64
  sensor_29_std: float64
  sensor_30_avg: float64
  sensor_30_max: float64
  sensor_30_min: float64
  sensor_30_std: float64
  sensor_31_avg: float64
  sensor_31_max: float64
  sensor_31_min: float64
  sensor_31_std: float64
  sensor_32_avg: float64
  sensor_32_max: float64
  sensor_32_min: float64
  sensor_32_std: float64
  sensor_33_avg: float64
  sensor_33_max: float64
  sensor_33_min: float64
  sensor_33_std: float64
  sensor_34_avg: float64
  sensor_34_max: float64
  sensor_34_min: float64
  sensor_34_std: float64
  sensor_35_avg: float64
  sensor_35_max: float64
  sensor_35_min: float64
  sensor_35_std: float64
  sensor_36_avg: float64
  sensor_36_max: float64
  sensor_36_min: float64
  sensor_36_std: float64
  sensor_37_avg: float64
  sensor_37_max: float64
  sensor_37_min: float64
  sensor_37_std: float64
  sensor_38_avg: float64
  sensor_38_max: float64
  sensor_38_min: float64
  sensor_38_std: float64
  sensor_39_avg: float64
  sensor_39_max: float64
  sensor_39_min: float64
  sensor_39_std: float64
  sensor_40_avg: float64
  sensor_40_max: float64
  sensor_40_min: float64
  sensor_40_std: float64
  sensor_41_avg: float64
  sensor_41_max: float64
  sensor_41_min: float64
  sensor_41_std: float64
  sensor_42_avg: float64
  sensor_42_max: float64
  sensor_42_min: float64
  sensor_42_std: float64
  sensor_43_avg: float64
  sensor_43_max: float64
  sensor_43_min: float64
  sensor_43_std: float64
  sensor_44_avg: float64
  sensor_44_max: float64
  sensor_44_min: float64
  sensor_44_std: float64
  sensor_45_avg: float64
  sensor_45_max: float64
  sensor_45_min: float64
  sensor_45_std: float64
  sensor_46_avg: float64
  sensor_46_max: float64
  sensor_46_min: float64
  sensor_46_std: float64
  sensor_47_avg: float64
  sensor_47_max: float64
  sensor_47_min: float64
  sensor_47_std: float64
  sensor_48_avg: float64
  sensor_48_max: float64
  sensor_48_min: float64
  sensor_48_std: float64
  sensor_49_avg: float64
  sensor_49_max: float64
  sensor_49_min: float64
  sensor_49_std: float64
  sensor_50_avg: float64
  sensor_50_max: float64
  sensor_50_min: float64
  sensor_50_std: float64
  sensor_51_avg: float64
  sensor_51_max: float64
  sensor_51_min: float64
  sensor_51_std: float64
  sensor_52_avg: float64
  sensor_52_max: float64
  sensor_52_min: float64
  sensor_52_std: float64
  sensor_53_avg: float64
  sensor_53_max: float64
  sensor_53_min: float64
  sensor_53_std: float64
  sensor_54_avg: float64
  sensor_54_max: float64
  sensor_54_min: float64
  sensor_54_std: float64
  sensor_55_avg: float64
  sensor_55_max: float64
  sensor_55_min: float64
  sensor_55_std: float64
  sensor_56_avg: float64
  sensor_56_max: float64
  sensor_56_min: float64
  sensor_56_std: float64
  sensor_57_avg: float64
  sensor_57_max: float64
  sensor_57_min: float64
  sensor_57_std: float64
  power_58_avg: float64
  power_58_max: float64
  power_58_min: float64
  power_58_std: float64
  wind_speed_59_avg: float64
  wind_speed_59_max: float64
  wind_speed_59_min: float64
  wind_speed_59_std: float64
  wind_speed_60_avg: float64
  wind_speed_60_max: float64
  wind_speed_60_min: float64
  wind_speed_60_std: float64
  wind_speed_61_avg: float64
  wind_speed_61_max: float64
  wind_speed_61_min: float64
  wind_speed_61_std: float64
  power_62_avg: float64
  power_62_max: float64
  power_62_min: float64
  power_62_std: float64
DORP_COLS: 
  - time_stamp
  - asset_id
  - id
  - train_test
TARGET_COLUMN: status_type_id
NORMAL_LABEL: 0
IDLING_LABEL: 2